version: 2

sphinx:
  fail_on_warning: true

python:
  version: "3.8"
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .
  system_packages: true

formats:
  - pdf
