version: 2

sphinx:
  fail_on_warning: false

python:
  version: "3.9"
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .

formats:
  - pdf
